# Generated by Django 6.0.2 on 2026-03-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('order_cancelled_by_user', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
