# Generated by Django 6.0.2 on 2026-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='order_final_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
