# Generated by Django 6.0.2 on 2026-03-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orderaddress_order_final_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='card_no',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
