# Generated by Django 6.0.2 on 2026-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentdetail_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='order_final_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
